# -*- coding: utf-8 -*-
"""
/***************************************************************************
Name:           catastroesp.py

                                 A QGIS plugin
Plugin:     catastroesp - Catastro de España
Purpose:    Gestion de HERRAMIENTAS DEL CATASTRO DE ESPAÑA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
        --------------------------------------------------------------------
        begin                : 2025-02-05
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Agustín Solabre Suárez
        email                : agusass@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QVariant, Qt, QSettings, QTranslator, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import (QAction, QApplication, QWidget, QPushButton, QMessageBox, QToolButton, QMenu, QToolBar,
                             QActionGroup)

from qgis.core import Qgis, QgsApplication
from qgis.gui import QgsMessageBar

import os.path
import processing

import sip

# Initialize Qt resources from file resources.py
from .resources import *

# Establecemos variables de usuario si no existen
from .settings import Settings           # CLASE DE CONFIGURACIÓN DE VARIABLES GLOBALES
initVAR = Settings().initVAR()
setVarUser = Settings().setVarUser()

from .config import configuration        # CLASE DE CONFIGURACIÓN DE VARIABLES DEL PROGRAMA
from .functions3 import Functions        # CLASE DE CONFIGURACIÓN DE FUNCIONES GENERALES

# CLASES EN FICHEROS INDEPENDIENTES
from .catastroBuscador import catastroBuscador                          # 01        BUSCADOR DE PARCELAS CATASTRALES
from .catastrotools import  (catastroToolINF,                           # 02        IDENTIFICADOR DE PARCELA CATASTRAL
                            catastroToolINF01,                          # 02.1      IDENTIFICADOR DE PARCELA CATASTRAL nuevo    ## TODO ## PRUEBA DE CAMBIO

                            catastroCargaMuni)                          # 03.1      CARGA CAPAS WEB o SHP DE CATASTRO MUNICIPIOS
from .catastrotools import  catastroCargaPARC                           # 03.11     CARGA PARCELAS                              #### TODO provisional ####
from .catastroHist import   catastroHist                                # 03.2      CARGA CATASTRO HISTORICO
from .catastroCargaMasiva import catastroCargaMasiva                    # 03.3      CARGA MASIVA DE PARCELAS CATASTRALES
from .catastroDescPolig import catastro_DescargaPOL                     # 03.4      CARGA CATASTRO POR POLÍGONO                 #### TODO provisional ####
# from .catastroDescPolig01 import catastro_DescargaPOL01               # 03.41                                                 #### TODO provisional #####
from .catastrotools import  (catastroBorraParc,                         # 03.5      BORRA PARCELA CON CURSOR
                            catastroASIGNA_RC)                          # 03.51     ASIGNA ATRIBUTOS DE PARCELA CATASTRAL A PARCELA PINCHADA
from .herrPoligIgualaAtributos import HerrPoligIgualaAtributos          # 03.52     ASIGNA ATTRS DE UNA CAPA A LA ACTIVA
from .herrAdaptaParcSuperf import herrAdaptaParcSuperf                  # 03.53     HERRAMIENTA PARA ADAPTAR PARCELAS A UNA SUPERFICIE
from .catastro_generaGML import catastro_generaGML                      # 03.6      GENERAR GML DESDE UN FICHERO DE POLÍGONOS
from .catastro_generaGMLconst import catastro_generaGMLconst            # 06.61     GENERAR GML DE CONSTRUCCION DESDE UN FICHERO DE POLÍGONOS
from .catastro_cargaXMLmasiva import catastro_cargaXMLmasiva            # 03.7      CARGA RESULTADO CONSULTA MASIVA
from .herr_CorrCapasPoligonos import herr_CorrCapasPoligonos            # 03.8      CORRECTOR DE POLÍGONOS
from .herr_depuraCuniasPoligonos import herr_depuraCuniasPoligonos      # 03.9      DEPURACIÓN CUÑAS DE POLIGONOS
from .geomGetlista import geomGetlista                                  # 03.10     LISTADO DE COORDENADAS DE UN POLÍGONO

from .cartoc_buscadorGeneral import cartoc_buscadorGeneral              # 04.1      MENU GENERAL DE BUSQUEDAS EN CARTOCIUDAD
from .puntoZ import puntoZ                                              # 04.2

from .gestorCapas import gestorCapas                                    # 05
from .borrarmarcadores import borrarmarcadores                          # 06
from .gestorCapas_ini import gestorCapas_ini                            # 07
from .catastro_config import catastro_config                            # 08
from .about_dialog import AboutDialog                                   # 09

####################################
##   VARIAS HERRAMIENTAS
####################################

from .catastro_config import reordenaVariables                                 #### TODO provisional #####
reordenaVariables.reordenaVariables()


class catastroesp:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.
        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Inicializa variables globales
        self.Sett = Settings()
        self.qs = QSettings()

        self.nombre_plugin = os.path.basename(os.path.dirname(__file__))

        uniProj = self.Sett.initVAR()
        global tipoUser

        # Inicializamos el proveedor de algoritmos
        self.provider = None                    # Esta variable almacenará el proveedor

        # Comprobamos el rol del usuario
        userSIG, tipoUser = self.Sett.entrarUser()

        msg = QMessageBox()
        text1 = u'- USUARIO: %s  -  TIPO: %s  -  UNIDAD: %s'%(userSIG, tipoUser, uniProj)
        text2 = u''
        msg.setIcon(QMessageBox.Information)
        # Devuelve el cursor a su estado natural
        QApplication.restoreOverrideCursor()
        iface.mainWindow().statusBar().showMessage(text1)

        # Save reference to the QGIS interface
        self.iface = iface

        # Carga de funciones generales y configuración de la aplicación
        self.fun = Functions()
        self.qs = QSettings()

        # initialize plugin directory. Directorio del plugin
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale. Variable de idioma
        localeST =  self.qs.value('locale/userLocale')
        locale = str(localeST)[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            f'{self.nombre_plugin}'+'_{}.qm'.format(locale))

        if os.path.exists(locale_path): # Ubicaciones traductor
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declaración de menús y barras de herramientas
        self.actions = []
        self.menu = self.tr(u'&Catastro de España')                 # Nombre de la barra de MENU
        self.toolbar = self.iface.addToolBar(u'Catastro de España') # Nombre de la barra de Herramientas


        self.grpmnuIdent       = self.tr(u'Herramientas de Identificación +')
        self.grpmnuHerrcat     = self.tr(u'Herramientas Catastrales +')

        # Diccionario para almacenar los submenús
        self.submenus = {}

        # Nombres de los submenús (se crearán dinámicamente)
        self.SUBMENU_INFO = self.tr(u'Herramientas Información')
        self.SUBMENU_CATASTRO = self.tr(u'Herramientas Catastrales')


        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    '''
    #----------------------------------------------------------------------------------------------------
    #       GENERADOR DE BARRA DE HERRAMIENTAS Y MENUS
    #----------------------------------------------------------------------------------------------------
    '''
    def initGui(self):
        ############################################################################
        ##     Creación de herramientas y entradas de menú  en el QGIS GUI        ##
        ############################################################################
        
        ## Se puede ocultar un icono en beta mediante esta expresión en 
        #   self.add_actionMenu, o self.add_action
        #            visible_flag=tipoUser == 'ADMINISTRADOR',

        # Crea y registra el proveedor cuando el plugin se inicializa
        QgsApplication.processingRegistry().addProvider(self.provider)

        #-------------------------------------------
        # 04 - 05 HERRAMIENTAS CATASTRALES SUELTAS
        #-------------------------------------------
        # Crear el grupo de acciones para herramientas sueltas
        self.solo_action_group = QActionGroup(self.iface.mainWindow())
        self.solo_action_group.setExclusive(True)  # Establecer que solo una acción puede estar activa a la vez

        # 01 BUSCADOR DE PARCELAS CATASTRALES
        self.buscParcCata = self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_buscador.jpg'),
            text=self.tr(u'Buscador de Parcelas Catastrales'),
            callback=self.catastroBuscador,
            parent=self.iface.mainWindow(),
            checkable=True)   # Hacemos que la acción sea "checkable"
        self.solo_action_group.addAction(self.buscParcCata)

        # 02 IDENTIFICADOR DE PARCELA CATASTRAL
        self.identParcCatatool = self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_identificador.jpg'),
            text=self.tr(u'Identificador de Parcela Catastral'),
            callback=self.catastroIdentificador,
            parent=self.iface.mainWindow(),
            checkable=True)   # Hacemos que la acción sea "checkable"
        self.solo_action_group.addAction(self.identParcCatatool)


        #--------------------------------------------------------------------------------------
        # 03.0 HERRAMIENTAS CATASTRALES en herramienta desplegable
        #--------------------------------------------------------------------------------------
        self.toolButtonCat = QToolButton()
        self.toolButtonCat.setObjectName('Herramientas de Catastro')
        self.toolButtonCat.setMenu(QMenu())
        self.toolButtonCat.setPopupMode(QToolButton.MenuButtonPopup)
        self.toolbar.addWidget(self.toolButtonCat)

        m = self.toolButtonCat.menu()       # Menú desplegable de HERRAMIENTAS CATASTRALES

        # 03.1 CARGA CAPAS POR MUNICIPIOS
        self.actionCat1 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_municipios.jpg'),
            text=self.tr(u'Carga capas del Catastro por Municipios'),
            callback=self.catastroCargaMuni,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.2 CARGA CATASTRO HISTORICO
        self.actionCat2 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_historico.jpg'),
            text=self.tr(u'Carga Catastro Historico'),
            callback=self.catastroCargaHist,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.3 CARGA MASIVA POR RC
        self.actionCat3 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_cargamasiva.jpg'),
            text=self.tr(u'Carga Masiva por RC de parcelas catastrales'),
            callback=self.catastroCargaMasiva,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.4 CARGA POR POLÍGONO
        self.actionCat4 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_poligon.jpg'),
            text=self.tr(u'Carga Catastro por Polígono'),
            callback=self.catastroDescPolig,
            parent=self.toolButtonCat,
            #### TODO provisional ###################
            # enabled_flag=tipoUser == 'ADMINISTRADOR',
            visible_flag=tipoUser == 'ADMINISTRADOR',
            #### TODO provisional ###################
            submenu=self.SUBMENU_CATASTRO)

        # 03.5 BORRA PARCELA CON CURSOR
        self.actionCat5 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_borraParc.jpg'),
            text=self.tr(u'Borra parcela catastral por cursor'),
            callback=self.catastroBorraParc,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.51 ASIGNA ATRIBUTOS
        self.actionCat51 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_asignaatrib.jpg'),
            text=self.tr(u'Asigna atributos de parcela catastral a parcela pinchada (PRUEBA)'),
            callback=self.catastroASIGNA_RC,
            parent=self.toolButtonCat,
            #### TODO provisional ###################
            # enabled_flag=tipoUser == 'ADMINISTRADOR',
            visible_flag=tipoUser == 'ADMINISTRADOR',
            #### TODO provisional ###################
            submenu=self.SUBMENU_CATASTRO)

        # 03.52 ASIGNA ATRIBUTOS ENTRE CAPAS
        self.actionCat52 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_asignaatrib.jpg'),
            text=self.tr(u'Asigna atributos de parcela de una capa a parcela pinchada en capa activa'),
            callback=self.herrPoligIgualaAtributos,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.53 ADAPTAR PARCELAS
        self.actionCat53 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/catastroesp.jpg'),
            text=self.tr(u'Herramienta para adaptar parcelas a una superficie (PRUEBA)'),
            callback=self.herrAdaptaParcSuperf,
            #### TODO provisional ###################
            # enabled_flag=tipoUser == 'ADMINISTRADOR',
            visible_flag=tipoUser == 'ADMINISTRADOR',
            #### TODO provisional ###################
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.6 GENERAR GML
        self.actionCat6 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_gml.jpg'),
            text=self.tr(u'Generar GML de parcelas desde un Fichero de polígonos'),
            callback=lambda: self.catastro_generaGML('CAT'),
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.61 GENERAR GML DE CONSTRUCCION
        self.actionCat61 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_gmlConst.jpg'),
            text=self.tr(u'Generar GML de CONSTRUCCIONES desde un Fichero de polígonos'),
            callback=lambda: self.catastro_generaGMLconst('CAT'),
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)
            
        # 03.7 CARGA CONSULTA MASIVA
        self.actionCat7 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_xml.jpg'),
            text=self.tr(u'Carga resultado Consulta catastral Masiva'),
            callback=self.catastro_cargaXMLmasiva,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.8 CORRECTOR DE POLÍGONOS (PRUEBA)
        self.actionCat81 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/C_icon.jpg'),
            text=self.tr(u'Corrector de Polígonos (PRUEBA)'),
            callback=self.herr_CorrCapasPoligonos,
            #### TODO provisional ###################
            # enabled_flag=tipoUser == 'ADMINISTRADOR',
            visible_flag=tipoUser == 'ADMINISTRADOR',
            #### TODO provisional ###################
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.9 DEPURACIÓN CUÑAS
        self.actionCat9 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_poligon.jpg'),
            text=self.tr(u'Depuración cuñas de poligonos'),
            callback=self.herr_depuraCuniasPoligonos,
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        # 03.10 LISTADO COORDENADAS POLÍGONO
        self.actionCat10 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_listPoligon.jpg'),
            text=self.tr(u'Listado de coordenadas de un polígono'),
            callback=lambda: self.geomGetlista('CAT'),
            parent=self.toolButtonCat,
            submenu=self.SUBMENU_CATASTRO)

        self.toolButtonCat.setDefaultAction(self.actionCat1)

        #-----------------------------------------------
        # 04.0 Herramientas del menú de IDENTIFICADORES
        #-----------------------------------------------
        self.toolButtonIndentificador = QToolButton()
        self.toolButtonIndentificador.setObjectName('Herramientas de Identificadores')
        self.toolButtonIndentificador.setMenu(QMenu())
        self.toolButtonIndentificador.setPopupMode(QToolButton.MenuButtonPopup)
        self.toolbar.addWidget(self.toolButtonIndentificador)

        m = self.toolButtonIndentificador.menu() # menú desplegable de Identificadores de Carreteras

        # 04.1 MENU GENERAL DE BUSQUEDAS EN CARTOCIUDAD
        self.actionInfo1 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cartociudad_buscar.jpg'),
            text=self.tr(u'Buscador en Cartociudad (IGN RT)'),
            callback=self.cartoc_buscadorGral,
            parent=self.toolButtonIndentificador,
            submenu=self.SUBMENU_INFO)

        # 04.2 IDENTIFICADORES Z DE PUNTO
        self.actionInfo2 = self.add_actionMenu(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/Z_icon.jpg'),
            text = self.tr(u'Identificador de Z y ubicación de un Punto'),
            callback=self.puntoZ,
            parent=self.toolButtonIndentificador,
            submenu=self.SUBMENU_INFO)

        self.toolButtonIndentificador.setDefaultAction(self.actionInfo1)

        #------------------------------------------------
        # 05 - 09 HERRAMIENTAS DIVERSAS POSTERIORES
        #------------------------------------------------
        # 05.0 CATALOGO DE CAPAS CARGABLES
        self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_capas_gis.jpg'),
            text=self.tr(u'Cargar catalogo Capas SIG'),
            callback=self.formularioCapas,
            parent=self.iface.mainWindow())

        # 06.0 BORRAR DATOS INCORPORADOS
        self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_borrarcapas.jpg'),
            text=self.tr(u'Borrar Marcadores y capas cargadas'),
            callback=self.borrarMarcadores,
            parent=self.iface.mainWindow())

        # 07.0 CARGAR CAPAS DE INICIO
        self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/catastroesp.jpg'),
            text=self.tr(u'Restaurar a inicio'),
            callback=self.formularioCapas_ini,
            #### TODO provisional ###################
            # enabled_flag=tipoUser == 'ADMINISTRADOR',
            visible_flag=tipoUser == 'ADMINISTRADOR',
            #### TODO provisional ###################
            parent=self.iface.mainWindow())

        # 08.0 CONFIGURACIÓN DE HERRAMIENTAS
        self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/cat_configuracion.jpg'),
            text=self.tr(u'Configurar Herramienta'),
            callback=self.configurador,
            parent=self.iface.mainWindow(),
            enabled_flag=True)

        # 09.0 AYUDA
        self.add_action(
            QIcon(f':/plugins/{self.nombre_plugin}/iconos/about.jpg'),
            text=self.tr(u'Ayuda de la aplicación'),
            callback=self.about,
            parent=self.iface.mainWindow(),
            enabled_flag=True)


        self.first_start = True

        # Se visualiza la barra de heramientas si está desactivada
        self.toolbar.setVisible(True)

    #----------------------------------------------------------------------------------------------------
    #----------------------------------------------------------------------------------------------------
    #----------------      RUTINAS GENERALES DE CREACIÒN DE BOTONERAS Y MENÚS         -------------------
    #----------------------------------------------------------------------------------------------------
    #----------------------------------------------------------------------------------------------------
    def get_submenu(self, submenu_name):
        """Obtiene o crea un submenú dentro del menú principal."""
        if submenu_name not in self.submenus:
            # Crear el submenú
            submenu = QMenu(submenu_name, self.iface.mainWindow())
            # Añadirlo al menú principal
            self.iface.addPluginToMenu(self.menu, submenu.menuAction())
            self.submenus[submenu_name] = submenu
        return self.submenus[submenu_name]

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        visible_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
        checkable=False,
        submenu=None):          # Nuevo parámetro para especificar submenú
        """ADD A TOOLBAR ICON TO THE TOOLBAR AND TO THE SPECIFIED SUBMENU."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)

        # Configurar estado
        action.setEnabled(enabled_flag)
        action.setVisible(visible_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if checkable:
            action.setCheckable(True)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu and submenu:
            # Añadir al submenú específico dentro del menú principal
            menu_sub = self.get_submenu(submenu)
            menu_sub.addAction(action)
        elif add_to_menu:
            # Si no se especifica submenú, va directamente al menú principal
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)
        return action


    def add_actionMenu(
        self,
        icon_path,
        text,
        callback,
        parent=None,
        enabled_flag=True,
        visible_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        checkable=False,
        submenu=None):          # Nuevo parámetro para especificar submenú
        """ADD A TOOLBAR MENU TO THE TOOLBAR AND TO THE SPECIFIED SUBMENU."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)

        # Configurar estado
        action.setEnabled(enabled_flag)
        action.setVisible(visible_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if checkable:
            action.setCheckable(True)

        if add_to_toolbar and parent:
            parent.menu().addAction(action)

        if add_to_menu and submenu:
            # Añadir al submenú específico dentro del menú principal
            menu_sub = self.get_submenu(submenu)
            menu_sub.addAction(action)

        self.actions.append(action)
        return action


    def add_submenu(self, submenu):
        # AÑADE UN SUBMENU A LA BARRA DE MENÚS
        icon = QIcon(f':/plugins/{self.nombre_plugin}/iconos/catastroesp.jpg')
        if self.PluginMenu != None:
            self.PluginMenu.addMenu(submenu)
        else:
            self.iface.addPluginToMenu(icon, self.menu, submenu.menuAction())


    def unload(self):
        # Eliminar todas las acciones del menú y la barra de herramientas
        for action in self.actions:
            try:
                self.iface.removePluginMenu(self.menu, action)
                self.iface.removeToolBarIcon(action)
            except RuntimeError:
                # Ignorar errores si el objeto ya ha sido eliminado
                pass
        self.actions = []

        # Eliminar la barra de herramientas si existe
        if hasattr(self, 'toolbar'):
            try:
                del self.toolbar
            except RuntimeError:
                # Ignorar errores si el objeto ya ha sido eliminado
                pass

        # Eliminar el proveedor de procesamiento si existe
        if hasattr(self, 'provider') and self.provider is not None:
            try:
                QgsApplication.processingRegistry().removeProvider(self.provider)
            except RuntimeError:
                # Ignorar errores si el objeto ya ha sido eliminado
                pass
            finally:
                self.provider = None  # Asegurarse de que el objeto se marque como eliminado


    def tr(self, message):
        """GET THE TRANSLATION FOR A STRING USING QT TRANSLATION API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate(f'{self.nombre_plugin}', message)


    '''
    #----------------------------------------------------------------------------------------------------
    #----------------------------------------------------------------------------------------------------
    #----------------          RUTINAS DE INICIO DE LAS FUNCIONALIDADES      ----------------------------
    #----------------------------------------------------------------------------------------------------
    #----------------------------------------------------------------------------------------------------
    '''



    #----------------------------------------------------------------------------------------------------
    #   05 RUTINAS DE HERRAMIENTAS DE CATASTRO
    #----------------------------------------------------------------------------------------------------

    def catastroBuscador(self):
        # 01 BUSCADOR DE PARCELAS CATASTRALES
        self.catastroBuscadorDlg = catastroBuscador(self.iface)
        result = self.catastroBuscadorDlg.exec_()

    def catastroIdentificador(self):
        # 02 IDENTIFICADOR DE PARCELA CATASTRAL
        self.identParcCatatool.setCheckable(True)    # Hacer que el botón sea seleccionable y exclusivo
        self.iface.messageBar().pushMessage(self.tr(u'IDENTIFICADOR DE PARCELA CATASTRAL'), self.tr(u'Pulsa en cualquier parcela'), level=Qgis.Info, duration=5)
        tool = catastroToolINF(self.iface.mapCanvas(),self.iface,self.identParcCatatool)
        self.iface.mapCanvas().setMapTool(tool)
        pass

    def catastroCargaMuni(self):
        # 03.1 CARGA CAPAS SHP DE CATASTRO
        self.actionCat1.setCheckable(True)    # Hacer que el botón sea seleccionable y exclusivo
        self.toolButtonCat.setDefaultAction(self.actionCat1)
        self.iface.messageBar().pushMessage(self.tr(u'CARGA CAPAS DE CATASTRO DE UN TÉRMINO MUNICIPAL'), self.tr(u'Pulsa en cualquier Término Municipal'), level=Qgis.Info, duration=5)
        tool = catastroCargaMuni(self.iface.mapCanvas(),self.iface,self.actionCat1)
        self.iface.mapCanvas().setMapTool(tool)
        pass

    def catastroCargaHist(self):
        # 03.2 CARGADOR DE CATASTROS HISTÓRICOS
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat2)
        self.dlg_catastroHist = catastroHist(self.iface)
        self.dlg_catastroHist.exec_()

    def catastroCargaMasiva(self):
        # 03.3 CARGA MASIVA DE PARCELAS CATASTRALES
        self.toolButtonCat.setDefaultAction(self.actionCat3)
        self.catastroCargaMasivaDlg = catastroCargaMasiva(self.iface)
        result = self.catastroCargaMasivaDlg.exec_()

    def catastroDescPolig(self):
        # 03.4 CARGADOR DE PARCELAS POR POLÍGONO
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat4)
        self.creaExpteEXPRODialog = catastro_DescargaPOL(self.iface)
        self.creaExpteEXPRODialog.exec_()

    def catastroBorraParc(self):
        # 03.5 Borra parcela catastral por cursor
        self.toolButtonCat.setDefaultAction(self.actionCat5)
        self.iface.messageBar().pushMessage(self.tr(u'Borra parcela catastral por cursor'), self.tr(u'Pulsa en cualquier parcela cargada'), level=Qgis.Info, duration=5)
        tool = catastroBorraParc(self.iface.mapCanvas(),self.iface,self.actionCat5)
        self.iface.mapCanvas().setMapTool(tool)
        pass
        
    def catastroASIGNA_RC(self):
        # 03.51 Asigna atributos de parcela catastral a parcela pinchada
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat51)
        self.iface.messageBar().pushMessage(self.tr(u'Asigna atributos de parcela catastral a parcela pinchada'), self.tr(u'Pulsa en cualquier parcela de capa de poligonos'), level=Qgis.Info, duration=5)
        tool = catastroASIGNA_RC(self.iface.mapCanvas(),self.iface,self.actionCat51)
        self.iface.mapCanvas().setMapTool(tool)
        
    def herrPoligIgualaAtributos(self):
        # 03.52 Asigna atributos de parcela de una capa a parcela pinchada en capa activa
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat52)
        self.iface.messageBar().pushMessage(self.tr(u'Asigna atributos de parcela de una capa a parcela pinchada en capa activa'), self.tr(u'Pulsa en cualquier parcela de capa de poligonos'), level=Qgis.Info, duration=5)
        self.herramienta_atributos = HerrPoligIgualaAtributos(self.iface, self.nombre_plugin)
        self.herramienta_atributos.initGui()

    def herrAdaptaParcSuperf(self):
        # 03.53 Herramienta para adaptar parcelas a una superficie
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat53)
        self.iface.messageBar().pushMessage(self.tr(u'Herramienta para adaptar parcelas a una superficie'), level=Qgis.Info, duration=5)
        self.herrAdaptaParcSuperf = herrAdaptaParcSuperf(self.iface)
        self.herrAdaptaParcSuperf.initGui()


    def catastro_generaGML(self, tipo):
        # 03.6 Genera GML
        if tipo == 'CAT':
            self.toolButtonCat.setDefaultAction(self.actionCat6)
        self.catastro_generaGMLDialog = catastro_generaGML(self.iface)
        result = self.catastro_generaGMLDialog.exec_()

    def catastro_generaGMLconst(self, tipo):
        # 03.61 Genera GML CONSTRUCCIONES
        QApplication.restoreOverrideCursor() # Restituye el cursor
        if tipo == 'CAT':
            self.toolButtonCat.setDefaultAction(self.actionCat61)
        self.catastro_generaGMLconstDialog = catastro_generaGMLconst(self.iface)
        self.catastro_generaGMLconstDialog.exec_()

    def catastro_cargaXMLmasiva(self):
        # 03.7 Carga resultado Consulta Masiva
        self.toolButtonCat.setDefaultAction(self.actionCat7)
        QApplication.setOverrideCursor(Qt.WaitCursor)         # ICONO DE ESPERA
        self.catastro_cargaXMLmasiva = catastro_cargaXMLmasiva(self.iface)
        QApplication.restoreOverrideCursor()
        pass

    def herr_CorrCapasPoligonos(self):
        # 03.8 CORRECTOR DE POLÍGONOS
        QApplication.restoreOverrideCursor() # Restituye el cursor
        self.toolButtonCat.setDefaultAction(self.actionCat81)
        self.herr_CorrCapasPoligonosDialog = herr_CorrCapasPoligonos(self.iface)
        self.herr_CorrCapasPoligonosDialog.exec_()

    def herr_depuraCuniasPoligonos(self):
        # 03.9 HERRAMIENTA DEPURACIÓN CUÑAS DE POLIGONOS
        self.toolButtonCat.setDefaultAction(self.actionCat9)
        self.iface.messageBar().pushMessage(self.tr(u'Depurador de cuñas en Polígonos'), self.tr(u'Depurador de cuñas en Polígonos'), level=Qgis.Info, duration=5)
        QApplication.setOverrideCursor(Qt.WaitCursor)   # ICONO DE ESPERA
        self.herr_depuraCuniasPoligonos = herr_depuraCuniasPoligonos(self.iface)
        QApplication.restoreOverrideCursor()            # ICONO NORMAL

    def geomGetlista(self, tipo):
        # 03.10 GEOMETRÍA DEL ELEMENTO PINCHADO DE UNA CAPA DE POLÍGONO
        self.toolButtonCat.setDefaultAction(self.actionCat10)
        self.iface.messageBar().pushMessage(self.tr(u'Listado coordenadas Polígono'), self.tr(u'Pulsa en el Mapa para obtener las coordenadas de un Polígono de la Capa Activa'), level=Qgis.Info, duration=5)
        tool = geomGetlista(self.iface.mapCanvas(), self.iface,self.actionCat10)
        self.iface.mapCanvas().setMapTool(tool)
        pass


    #----------------------------------------------------------------------------------------------------
    #   04.0 RUTINAS DE HERRAMIENTAS DE BÚSQUEDAS
    #----------------------------------------------------------------------------------------------------

    def cartoc_buscadorGral(self):
        # 04.1 MENU GENERAL DE BUSQUEDAS EN CARTOCIUDAD
        self.toolButtonIndentificador.setDefaultAction(self.actionInfo1)
        self.dlg_cartoc_buscadorGENERAL = cartoc_buscadorGeneral(self.iface)
        result = self.dlg_cartoc_buscadorGENERAL.exec_()
        pass

    def puntoZ(self):
        # 04.2 Z DE UN PUNTO
        self.toolButtonIndentificador.setDefaultAction(self.actionInfo2)
        self.iface.messageBar().pushMessage(self.tr(u'Z de un punto'), self.tr(u'Pulsa un punto para obtener su Z'), level=Qgis.Info, duration=5)
        tool = puntoZ(self.iface.mapCanvas(), self.iface,self.actionInfo2)
        self.iface.mapCanvas().setMapTool(tool)
        pass


    #----------------------------------------------------------------------------------------------------
    #   RESTO DE RUTINAS
    #----------------------------------------------------------------------------------------------------
    def formularioCapas(self):
        # 05 CATALOGO DE CAPAS CARGABLES
        self.dlg_gestorCapas = gestorCapas(self.iface)
        result = self.dlg_gestorCapas.exec_()
        pass

    def borrarMarcadores(self):
        # 06 BORRAR DATOS INCORPORADOS
        self.dlg_borrarmarcadores = borrarmarcadores(self.iface)
        result = self.dlg_borrarmarcadores.exec_() #Esta linea es para tirar del menú externo
        pass

    def formularioCapas_ini(self):
        # 07 CATALOGO DE CAPAS CARGABLES INICIALES
        self.dlg_gestorCapas_ini = gestorCapas_ini(self.iface)
        result = self.dlg_gestorCapas_ini.exec_()
        pass

    def configurador(self):
        # 08 CONFIGURACIÓN DE HERRAMIENTAS
        # El config apunta a la pestaña GENERAL
        self.dlg_config = catastro_config(self.iface, tabConfig = 0)
        result = self.dlg_config.exec_()
        pass

    def about(self):
        # 09 AYUDA
        self.dlg_about = AboutDialog(self.iface)
        result = self.dlg_about.exec_()
        pass

    ##########################################################################################

    def todo(self):
        # 00 NO HACE NADA. HERRAMIENTAS EN DESARROLLO
        self.fun.showMessage("Herramienta en desarrollo")
        pass
